### ISSUE TITLE
java.lang.NoSuchMethodError on AndroidOS

### ISSUE THREAD

**Issue by i-sakurada** [paypay/paypayopa-sdk-java#158]
**Describe the bug**
An error occurred in Payment Api.

java.lang.NoSuchMethodError: No virtual method getAnnotatedType()Ljava/lang/reflect/AnnotatedType; in class Ljava/lang/reflect/Field; or its super classes (declaration of 'java.lang.reflect.Field' appears in /system/framework/core-oj.jar)

**To Reproduce**
**Expected behavior**

I coded according to "DynamicQRCode.md".
Running on Junit is success , but Running on Simulator(Pixel API 26) is fail cause by "java.lang.NoSuchMethodError: No virtual method getAnnotatedType()Ljava/lang/reflect/AnnotatedType".

This class is not supported on AndroidOS.
https://developer.android.com/reference/java/lang/reflect/Method 

**Err Details**

java.lang.NoSuchMethodError: No virtual method getAnnotatedType()Ljava/lang/reflect/AnnotatedType; in class Ljava/lang/reflect/Field; or its super classes (declaration of 'java.lang.reflect.Field' appears in /system/framework/core-oj.jar)
        at org.hibernate.validator.internal.properties.javabean.JavaBeanField.getAnnotatedType(JavaBeanField.java:74)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findCascadingMetaData(AnnotationMetaDataProvider.java:640)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findPropertyMetaData(AnnotationMetaDataProvider.java:239)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getFieldMetaData(AnnotationMetaDataProvider.java:228)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.retrieveBeanConfiguration(AnnotationMetaDataProvider.java:129)
E/FinancialApplication:     at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.<init>(AnnotationMetaDataProvider.java:105)
        at org.hibernate.validator.internal.metadata.BeanMetaDataManagerImpl.<init>(BeanMetaDataManagerImpl.java:133)
        at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.lambda$createValidator$0(ValidatorFactoryImpl.java:320)
        at org.hibernate.validator.internal.engine.-$$Lambda$ValidatorFactoryImpl$S6RhicpRYZvQEqVoWrAQI_4SXi8.apply(Unknown Source:10)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1715)
        at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.createValidator(ValidatorFactoryImpl.java:311)
        at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.getValidator(ValidatorFactoryImpl.java:210)
        at jp.ne.paypay.Validator.getValidator(Validator.java:15)
        at jp.ne.paypay.Validator.validate(Validator.java:29)
        at jp.ne.paypay.api.PaymentApi.createQRCode(PaymentApi.java:177)

**Environment (please complete the following information):**
 - OS: [AndroidOS8.0 and AndroidOS11]
 - App: Android native app ( apk )

**Additional context**
Cloud you tell me how to solve? Or I want you to fix the bug.
I hope for your sincere response, thank you.

**Comment by curtisfennerpaypay** [comment]
Please take note that you generally should not run an SDK like this on a user's mobile device. That is because the SDK requires your API secret, and you must not deliver your API secret to an untrusted user's device. Please do not use the SDK in a mobile app intended for end-users; you will instead need to store your API secret in a backend service.

----

The PayPay Java SDK uses Jakarta Bean Validation to validate request objects as a convenience for making developing applications with the SDK easier. As you have found, the `hibernate-validation` implementation of Jakarta Bean Validation does not fully support Android because Android is missing some methods required by Java.

If you find an alternative implementation of the Jakarta Bean Validation spec for Android, you could use that.

----

We could implement a feature to let you enable or disable the `Validator` class for api classes. By turning off the validator, the SDK would function on Android, but without the convenience of client-side request validation. This won't be a high priority but I will add it to the backlog.
